MTGDeck/Models/Card.cs
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace MTGDeck.Models
{
    public class Card
    {
      public Card()
      {
        this.JoinEntities = new HashSet<CardDeck>();
      }
        public int CardId { get; set; }
        public string Name { get; set; }
        [NotMapped]
        public Prices Prices { get; set; }
        [NotMapped]
        public Legalities Legalities { get; set; }
        public string Mana_Cost { get; set; }
        [NotMapped]
        public string[] Colors { get; set; }
        public string ColorsAsString() { 
            string s = "";
            for (int i = 0; i < (Colors?.Length ?? 0); i++) {
              s += Colors[i];
              s += " ";
            }
            return s;
            }
        public string Type_Line { get; set; }
        public string Set_Name { get; set; }
        public virtual ICollection<CardDeck> JoinEntities {get; set; } 

    public static List<Card> SearchCards(string name, string colors, string type)
    {
      var apiCallTask = ApiHelper.Search(name, colors, type);
      var result = apiCallTask.Result;
      if (result == "No cards found.")
      {
          return new List<Card> { };
      }
      else
      { 
        JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
        List<Card> cardList = JsonConvert.DeserializeObject<List<Card>>(jsonResponse["data"].ToString());
        return cardList;
      }
    }
    public static Card GetCard(string name)
    {
      Card card = ApiHelper.GetCard(name).Result;
      return card;
    }
    public static string GetCardImage(string name)
    {
      ScryfallCard card = ApiHelper.GetScryfallCard(name).Result;
      string imageUrl = card.image_uris["border_crop"];
      return imageUrl;
    }  
    public static string GetLegalities(string name)
    {
      ScryfallCard card = ApiHelper.GetScryfallCard(name).Result;
      string legalities = "";
      foreach((string format, string legality) in card.legalities)
      {
        legalities += $"{format}: {legality}, ";
      }
      return legalities;
    }  
    public static string GetPrices(string name)
    {
      ScryfallCard card = ApiHelper.GetScryfallCard(name).Result;
      string prices = "";
      foreach((string currency, string value) in card.prices)
      {
        prices += $"{currency}: {value}, ";
      }
      return prices;
    }  
    public static string GetOracle(string name)
    {
      ScryfallCard card = ApiHelper.GetScryfallCard(name).Result;
      string oracle = card.Oracle_Text;
      return oracle;
    }  
    public static string GetFlavor(string name)
    {
      ScryfallCard card = ApiHelper.GetScryfallCard(name).Result;
      string flavor = card.Flavor_Text;
      return flavor;
    }
  }

    public partial class ImageUris
    {
        [JsonProperty("border_crop")]
        public Uri BorderCrop { get; set; }
    }
  public partial class Legalities
  {
      [JsonProperty("standard")]
      public string Standard { get; set; }

      [JsonProperty("future")]
      public string Future { get; set; }

      [JsonProperty("historic")]
      public string Historic { get; set; }

      [JsonProperty("gladiator")]
      public string Gladiator { get; set; }

      [JsonProperty("pioneer")]
      public string Pioneer { get; set; }

      [JsonProperty("explorer")]
      public string Explorer { get; set; }

      [JsonProperty("modern")]
      public string Modern { get; set; }

      [JsonProperty("legacy")]
      public string Legacy { get; set; }

      [JsonProperty("pauper")]
      public string Pauper { get; set; }

      [JsonProperty("vintage")]
      public string Vintage { get; set; }

      [JsonProperty("penny")]
      public string Penny { get; set; }

      [JsonProperty("commander")]
      public string Commander { get; set; }

      [JsonProperty("brawl")]
      public string Brawl { get; set; }

      [JsonProperty("historicbrawl")]
      public string Historicbrawl { get; set; }

      [JsonProperty("alchemy")]
      public string Alchemy { get; set; }

      [JsonProperty("paupercommander")]
      public string Paupercommander { get; set; }

      [JsonProperty("duel")]
      public string Duel { get; set; }

      [JsonProperty("oldschool")]
      public string Oldschool { get; set; }

      [JsonProperty("premodern")]
      public string Premodern { get; set; }
  }
   public partial class Prices
    {
        [DisplayName("USD")]
        [JsonProperty("usd")]
        public string Usd { get; set; }

        [DisplayName("USD Foil")]
        [JsonProperty("usd_foil")]
        public string UsdFoil { get; set; }

        [DisplayName("EUR")]
        [JsonProperty("eur")]
        public string Eur { get; set; }

        [DisplayName("EUR Foil")]
        [JsonProperty("eur_foil")]
        public string EurFoil { get; set; }
    }
}

MTGDeck/Controllers/CardsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using MTGDeck.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace MTGDeck.Controllers
{
  [Authorize]
  public class CardsController : Controller
  {
    private readonly MTGDeckContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public CardsController(UserManager<ApplicationUser> userManager, MTGDeckContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public IActionResult Search(string name, string color, string type)
    {
    List<Card> result = Card.SearchCards(name, color, type);
    // ViewBag.NoCards = "test";
    
    return View(result);
    }
    public IActionResult GetCard(string name)
    {
      Card result = Card.GetCard(name);
      return View(result);
    }

    [AllowAnonymous]
    public IActionResult Index()
        {
            var allCards = Card.SearchCards("", "", "elf");
            return View(allCards);
        }
    [AllowAnonymous]
    public IActionResult Details(string name)
    {
      Card card = Card.GetCard(name);
      storeCardInfo(name);
      ViewBag.DeckId = new SelectList(_db.Decks, "DeckId", "Name");
      return View(card);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCard = _db.Cards.FirstOrDefault(card => card.CardId == id);
      _db.Cards.Remove(thisCard);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCard(int joinId)
    {
      var joinEntry = _db.CardDecks.FirstOrDefault(entry => entry.CardDeckId == joinId);
      _db.CardDecks.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // Grabs the extra info stored in ScryfallCard and assignes passes them to the ViewBag
    public void storeCardInfo(string cardName)
        {
            string cardImages = Card.GetCardImage(cardName);
            ViewBag.CardImages = Url.Content(cardImages);
            string[] cardLegalities = Card.GetLegalities(cardName).Replace("_", " ").Split(", ");
            ViewBag.CardLegalities = cardLegalities;
            string[] cardPrices = Card.GetPrices(cardName).Replace("_", " ").Split(", ");
            ViewBag.CardPrices = cardPrices;
            string cardOracle = Card.GetOracle(cardName);
            ViewBag.CardOracle = cardOracle;
            string cardFlavor = Card.GetFlavor(cardName);
            ViewBag.CardFlavor = cardFlavor;
        }
  }
}

MTGDeck/Controllers/DecksController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using MTGDeck.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System;

namespace MTGDeck.Controllers
{
    [Authorize]
  public class DecksController : Controller
  {
    private readonly MTGDeckContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public DecksController(UserManager<ApplicationUser> userManager, MTGDeckContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userDecks = _db.Decks.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userDecks);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public async Task<ActionResult> Create(Deck deck, int cardId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      deck.User = currentUser;
      _db.Decks.Add(deck);
      _db.SaveChanges();
      if (cardId != 0)
      {
          _db.CardDecks.Add(new CardDeck() { CardId = cardId, DeckId = deck.DeckId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDeck = _db.Decks
          .Include(deck => deck.JoinEntities)
          .ThenInclude(join => join.Deck)
          .FirstOrDefault(deck => deck.DeckId == id);
      return View(thisDeck);
    } 

    public ActionResult Edit(int id)
    {
      Deck deck = _db.Decks.FirstOrDefault(model => model.DeckId == id);
      return View(deck);
    }
    [HttpPost]
    public ActionResult Edit(Deck deck)
    {
      _db.Entry(deck).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = deck.DeckId });
    }
    public ActionResult Delete(int id)
    {
      var thisDeck = _db.Decks.FirstOrDefault(deck => deck.DeckId == id);
      return View(thisDeck);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDeck = _db.Decks.FirstOrDefault(deck => deck.DeckId == id);
      _db.Decks.Remove(thisDeck);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddCard(Card card, Deck deck, int DeckId, int CardId)
    {
      Console.WriteLine("=========" + card.Name + "==========");
      Console.WriteLine("=========" + DeckId + "=========");
      _db.Cards.Add(card);
      _db.SaveChanges();
      if (DeckId != 0)
      {
      _db.CardDecks.Add(new CardDeck() { CardId = card.CardId, DeckId = deck.DeckId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    // [HttpPost, ActionName("DeleteCard")]
    public ActionResult DeleteCard(int joinId)
    {
      var joinEntry = _db.CardDecks.FirstOrDefault(entry => entry.CardDeckId == joinId);
      var thisDeck = joinEntry.Deck;
      var thisCard = joinEntry.Card;
      _db.CardDecks.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

    //   public ActionResult DeleteCard(int joinId)
    // {
    //   var joinEntry = _db.CardDecks.FirstOrDefault(entry => entry.CardDeckId == joinId);
    //   var thisDeck = joinEntry.Deck;
    //   var thisCard = joinEntry.Card;
    //   // thisDeck.RemoveManaCost(thisCard);
    //   thisDeck.RemoveLand(thisCard);
    //   _db.CardDecks.Remove(joinEntry);
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
}

MTGDeck/Views/Cards/Details.cshtml
<!-- GetCard(searchName)
All of this info can be accessed by using the ViewBags below
ViewBag.CardImages, ViewBag.CardLegalities, ViewBag.CardPrices, ViewBag.CardOracle, ViewBag.CardFlavor
This is how you can use the url in the viewbag
<img id="img_logo" alt="Logo" src="@Url.Content(ViewBag.CardImages)"/> -->
@{
  Layout = "_Layout";
}

@using MTGDeck.Models;
@model Card;

<div id="cardImagePage" class="d-flex justify-content-center">
  <div id="cardNameDisplay">
    <h3>@Model.Name</h3>
  </div>
  <div id="cardImage">
    <img alt="Card image" src="@Url.Content(ViewBag.CardImages)"/>
  </div>
  
  <!-- Here, we're passing in both the card info and the deck info to first save the card to the DB, then create the join entity -->
  @using (Html.BeginForm("AddCard", "Decks"))
  {
    @Html.Label("Select Deck")
    @Html.DropDownList("DeckId")

    @Html.HiddenFor(model => model.Name);
    @Html.HiddenFor(model => model.Mana_Cost);
    @Html.HiddenFor(model => model.Type_Line);
    @Html.HiddenFor(model => model.Set_Name);

    <input type="submit" value="Add to deck" class="btn btn-primary btn-sm" />
    <p>@Html.ActionLink("Create a new deck", "Create", "Decks")</p>
  }
</div>
  <div class="row">
    <div class="col-4">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">+</th>
            <th scope="col">Legality</th>
          </tr>
        </thead>
        <tbody>
          @for (int i = 0; i <= 9; i++) 
          {
              <tr>
                <td scope="row">@(i+1)</td>
                <td>@ViewBag.CardLegalities[i]</td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  <div class="col-4">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">+</th>
          <th scope="col">Legality</th>
        </tr>
      </thead>
      <tbody>
        @for (int j = 10; j <= 18; j++) 
        {
            <tr>
              <td scope="row">@(j+1)</td>
              <td>@ViewBag.CardLegalities[j]</td>
          </tr>
        }
      </tbody>
    </table>
  </div>
  <div class="col-4">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">+</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
        @for (int i = 0; i < ViewBag.CardPrices.Length-1; i++)
        {
          <tr>
            <td scope="row">@(i+1)</td>
            <td>@ViewBag.CardPrices[i]</td>
          </tr>
        }
      </tbody>
    </table>
  </div>
</div>

MTGDeck/Views/Cards/GetCard.cshtml
@{
  Layout = "_Layout";
}

@using MTGDeck.Models;
@model MTGDeck.Models.Card

  <div class="row row-cols-2 row-cols-md-2 g-4">
    <ul>
        <li>@Html.ActionLink($"{Model.Name}", "Details", new { name = Model.Name })</li>
        <li>@Model.Type_Line</li>
        <li>@Model.Set_Name</li>
        <li>@Model.Mana_Cost</li>
    </ul>
  </div>

MTGDeck/Views/Cards/Index.cshtml
@{
  Layout = "_Layout";
}

@using MTGDeck.Models;
@model IEnumerable<MTGDeck.Models.Card>
<style>
body {
  background-image: url('https://get.wallhere.com/photo/sky-clouds-fantasy-city-ArtStation-artwork-fantasy-art-1747289.jpg');
}
</style>

<div class="search-content container-fluid">
  <div class="row">
    <!-- <div class="col">
      @using(Html.BeginForm("GetCard", "Cards"))
      {
        @Html.Label("Get Card by Name")
        @Html.TextBox("name")
        <input type="submit" value="GetCard" class="btn btn-primary btn-sm"/>
      }
    </div> -->
    <div class="col-6">
      @using(Html.BeginForm("Search", "Cards"))
      {
        <div style="margin-bottom: 5px;" class="row">
          <div  class="col">
            @Html.Label("Search All by Name")
          </div>
          <div class="col">
            @Html.TextBox("name")
          </div>
        </div>
        <div style="margin-bottom: 5px;" class="row">
          <div class="col">
            @Html.Label("Search by Color")
          </div>
          <div class="col">
            @Html.DropDownList("color", new List<SelectListItem>
            {
              new SelectListItem { Text = "Black", Value = "B"},
              new SelectListItem { Text = "Blue", Value = "U"},
              new SelectListItem { Text = "Red", Value = "R"},
              new SelectListItem { Text = "White", Value = "W"},
              new SelectListItem { Text = "Green", Value = "G"},
              }, "Select Color", new { @style = "width:163px;" })
          </div>
        </div>
        <div style="margin-bottom: 5px;" class="row">
          <div class="col">
            @Html.Label("Search by Type")
          </div>
          <div class="col">
            @Html.TextBox("type")
          </div>
        </div>
          <input type="submit" value="Search" class="btn btn-primary btn-sm" style="margin-top: 5px; width: 25%"/>
      }
    </div>
  </div>
</div>
  <div class="row row-cols-2 row-cols-md-2 g-4" id="cardsDiv" class="d-flex justify-content-center">
    <!-- <div class="cardsBackground" style="height: 100vh"> </div> -->
    @foreach (Card card in Model)
    {
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="~/images/circle_full_set.svg" alt="Elemental magic orbs" style="height: 8rem;">
        <div class="card-body">
          <p class="card-text">@Html.ActionLink($"{card.Name}", "Details", new { name = card.Name })</p>
        </div>
      </div>
    }
  </div>







  

MTGDeck/Views/Cards/Search.cshtml
@{
  Layout = "_Layout";
}

@using MTGDeck.Models;
@model List<Card>

<h3>Search Results:</h3>
    @if (Model.Count() != 0)
    {
      @foreach (Card card in Model)
      {
        <div class="card-content">
          <p>@Html.ActionLink($"{card.Name}", "Details", new { name = card.Name })</p>
          <p>@card.Type_Line</p>
          <p>@card.Set_Name</p>
          <p>@card.Mana_Cost</p>
        </div>
      }
    }
    else
    {
      <p>"No cards found!"</p>
    }

MTGDeck/Views/Cards/SearchResults.cshtml
@{
  Layout = "_Layout";
}

@using MTGDeck.Models;
@model IEnumerable<MTGDeck.Models.Card>


<div class="row row-cols-2 row-cols-md-2 g-4">
    @foreach (Card card in Model)
    {
      <li>@Html.ActionLink($"{card.Name}", "Details", new { name = card.Name })</li>
      @* <li>@Html.ActionLink($"{card.Colors}", "Details", new { color = card.Colors })</li>
      <li>@Html.ActionLink($"{card.Type_Line}", "Details", new { type = card.Type_Line })</li> *@
    }
  </ul>